### PR TITLE
Custom Radio Buttons for the Bootstrap Template

### PR DESCRIPTION
**Pull request by zcadditions**

### CODE REVIEW

**Comment by lat9** [comment]
Part of the solution for #118.

**Comment by lat9** [comment]
Note that `tpl_modules_opc_address_block.php` will require similar changes to accommodate the `gender` button.

**Comment by zcadditions** [comment]
is that a new file?

Okay, I see it in my fork but not what I downloaded from ZC

**Comment by lat9** [comment]
Right, the version up on the ZC plugins is v1.5.0.  That address-formatting module is part of v2.0.0, which incorporates guest-checkout.

**Pull request merged**
