### PR TITLE
Simplify the confirmation page's checking, making it easier for add-on payment modules to integrate

### PR DESCRIPTION
**Pull request by lat9**
See #394 for additional information.

### CODE REVIEW

**Comment by proseLA** [comment]
ok, i have seemingly played around a bit more with this PR, and i plan to put into production on a clients site.  i think it is an improvement.  

it still does not work properly with affirm, and i am not sure that it ever will, as it requires more thought for affirm.

the issue with affirm is that upon a successful approval, [the affirm javascript redirects to a confirmation page.](https://docs.affirm.com/developers/reference/the-merchant-object#:~:text=user_confirmation_url,the%20POST%20request.)  i have not found a way for this redirect to have the post data from the `checkout_one` page.  which is a problem.

as a situation would have it, i have been working on a 3ds implementation for a different payment module, and by only adding the `checkout_one_confirmation` page to the allowed pages for loading the javascript, the payment module works exactly the same as the standard ZC 3 step checkout.  which is great.  but that module does not do any redirects; the javascript runs, returns some vars, and then i'm adding it to the page without any redirects or reloads.

**Comment by proseLA** [comment]
ok, i am no longer a fan on this PR.

for whatever reason, right here:

https://github.com/lat9/one_page_checkout/blob/30e0ccdf6ab35fba11d466c5d8a369220e8e6794/includes/modules/pages/checkout_one_confirmation/header_php.php#L163

the count of shipping modules is coming back as 0.

my session var looks like:

image

there is a LOT of extra stuff in this PR which makes it hard for me to isolate where the problem might be.  i think i have installed this PR correctly.  when  i go back to a straight OPC 2.4.6 the count comes back as 1, and no problem.

**Comment by lat9** [comment]
@proseLA, what's the base Zen Cart version?

**Comment by proseLA** [comment]
according to the server info, 1.5.7c.  

tested under php 7.3 and 8.0.

**Comment by lat9** [comment]
> ok, i am no longer a fan on this PR.
> 
> for whatever reason, right here:
> 
> https://github.com/lat9/one_page_checkout/blob/30e0ccdf6ab35fba11d466c5d8a369220e8e6794/includes/modules/pages/checkout_one_confirmation/header_php.php#L163
> 
> the count of shipping modules is coming back as 0.
> 
> my session var looks like:
> 
> image
> 
> there is a LOT of extra stuff in this PR which makes it hard for me to isolate where the problem might be. i think i have installed this PR correctly. when i go back to a straight OPC 2.4.6 the count comes back as 1, and no problem.

Noting that `zen_count_shipping_modules` doesn't check `$_SESSION['shipping']`, it looks for the shipping modules that are configured and then to see if any of those configured modules are (a) instantiated globally and (b) enabled.  For the case given, that would be the presence of a `upsoauth` element with its `enabled` attribute set to (bool)true.

**Pull request merged**
